# Generated by Django 4.2.4 on 2023-09-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productor',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='productor',
            name='user',
        ),
        migrations.AddField(
            model_name='productor',
            name='apellido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='dni',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='domicilio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productor',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
