# Generated by Django 4.2.4 on 2023-09-13 22:51

from django.db import migrations
import shared.models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", shared.models.UserManagerWrapper()),
            ],
        ),
    ]
