# Generated by Django 4.2.4 on 2023-09-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precioXUnidad', models.FloatField(default=0)),
                ('precioXKg', models.FloatField(default=0)),
                ('descripcion', models.CharField(max_length=50)),
                ('organico', models.BooleanField()),
                ('f_almacenamiento', models.DateField(auto_now_add=True)),
                ('destacado', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
        ),
    ]
